version: 2.1
parameters:
  version:
    type: string
    default: none

orbs:
  c: rafaelostertag/common-orb@1.12.0

workflows:
  version: 2
  deploy-services:
    when:
      not:
        or:
          - equal: [ none, <<pipeline.parameters.version>> ]
          - equal: [ "", <<pipeline.parameters.version>> ]
    jobs:
      - c/deploy-with-helm:
          name: deploy image server
          namespace: imageserver
          release: imageserver
          chart: helm/imageserver
          version: <<pipeline.parameters.version>>
